theme: jekyll-theme-minimal
title: 'Machine Learning Resources'

description: 'Bunch of resources and tutorials on machine learning'

navbar-links:
  About Me: "A coputer science enthusiast"
  Author's home: "sauravshah.com.np/new"

#avatar: "/img/avatar-icon.png"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: Saurav Shah

social-network-links:
  rss: true
  email: "sauravshah.31@gmail.com"
  github: sauravshah31
  linkedin: sauravshah-
copyright: '❤ No Copyright ❤'
share-links-active:
  twitter: true
  facebook: true
  linkedin: true  


exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile


plugins:
  - jekyll-paginate
  - jekyll-sitemap


nav:
- Preface: index.md
- Week 0: practiseQuestions/assignment_week0.html
